// <auto-generated />
using System;
using HotelConsagradoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelConsagradoAPI.Migrations
{
    [DbContext(typeof(HotelConsagradoDbContext))]
    partial class HotelConsagradoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("HotelConsagradoAPI.Models.Hospede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReservaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("HotelConsagradoAPI.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeAdultos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeCriancas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeQuartos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefoneResponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelConsagradoAPI.Models.Hospede", b =>
                {
                    b.HasOne("HotelConsagradoAPI.Models.Reserva", "Reserva")
                        .WithMany("Hospedes")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("HotelConsagradoAPI.Models.Reserva", b =>
                {
                    b.Navigation("Hospedes");
                });
#pragma warning restore 612, 618
        }
    }
}
