// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAPI.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250427151343_AlgumasValidacoesNoModelHospede")]
    partial class AlgumasValidacoesNoModelHospede
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("HotelAPI.Models.Hospede", b =>
                {
                    b.Property<int>("HospedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CPF")
                        .HasMaxLength(11)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HospedeId");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("HotelAPI.Models.Quarto", b =>
                {
                    b.Property<int>("QuartoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Preco")
                        .HasColumnType("REAL");

                    b.HasKey("QuartoId");

                    b.ToTable("Quartos");
                });

            modelBuilder.Entity("HotelAPI.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospedeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservaId");

                    b.HasIndex("HospedeId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelAPI.Models.Reserva", b =>
                {
                    b.HasOne("HotelAPI.Models.Hospede", "Hospede")
                        .WithMany("Reservas")
                        .HasForeignKey("HospedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospede");
                });

            modelBuilder.Entity("HotelAPI.Models.Hospede", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
